#/home/william/CPP/Projects/RayTracer2/src /home/william/CPP/Projects/RayTracer2/test 
#/home/william/CPP/Projects/RayTracer2/test/TestAll.cpp
#/home/william/CPP/Projects/RayTracer2/
#/usr/local/lib/
#cppunit
HEADERS := /home/william/CPP/Projects/RayTracer2/src/utils/Utils.h /home/william/CPP/Projects/RayTracer2/test/utils/TestUtils.h  /home/william/CPP/Projects/RayTracer2/src/geometry/Tuple.h /home/william/CPP/Projects/RayTracer2/test/geometry/TestTuple.h  /home/william/CPP/Projects/RayTracer2/src/geometry/Matrix.h /home/william/CPP/Projects/RayTracer2/test/geometry/TestMatrix.h  /home/william/CPP/Projects/RayTracer2/src/utils/Colour.h /home/william/CPP/Projects/RayTracer2/test/utils/TestColour.h  /home/william/CPP/Projects/RayTracer2/src/geometry/Ray.h /home/william/CPP/Projects/RayTracer2/test/geometry/TestRay.h  /home/william/CPP/Projects/RayTracer2/src/scene/world/object/material/Material.h /home/william/CPP/Projects/RayTracer2/src/scene/world/object/shape/Shape.h /home/william/CPP/Projects/RayTracer2/test/scene/world/object/material/TestMaterial.h 
OBJS := /home/william/CPP/Projects/RayTracer2/test/build/Utils.o /home/william/CPP/Projects/RayTracer2/test/build/TestUtils.o /home/william/CPP/Projects/RayTracer2/test/build/Tuple.o /home/william/CPP/Projects/RayTracer2/test/build/TestTuple.o /home/william/CPP/Projects/RayTracer2/test/build/Matrix.o /home/william/CPP/Projects/RayTracer2/test/build/TestMatrix.o /home/william/CPP/Projects/RayTracer2/test/build/Colour.o /home/william/CPP/Projects/RayTracer2/test/build/TestColour.o /home/william/CPP/Projects/RayTracer2/test/build/Ray.o /home/william/CPP/Projects/RayTracer2/test/build/Material.o /home/william/CPP/Projects/RayTracer2/test/build/Shape.o /home/william/CPP/Projects/RayTracer2/test/build/TestRay.o /home/william/CPP/Projects/RayTracer2/test/build/TestMaterial.o

/home/william/CPP/Projects/RayTracer2/test/TestAll: $(OBJS) $(HEADERS) /home/william/CPP/Projects/RayTracer2/test/TestAll.cpp
	g++ /home/william/CPP/Projects/RayTracer2/test/TestAll.cpp $(OBJS) -o /home/william/CPP/Projects/RayTracer2/test/TestAll.out -I/home/william/CPP/Projects/RayTracer2/ -L/usr/local/lib/ -lcppunit

/home/william/CPP/Projects/RayTracer2/test/build/Utils.o: /home/william/CPP/Projects/RayTracer2/src/utils/Utils.cpp $(HEADERS)
	g++ -c /home/william/CPP/Projects/RayTracer2/src/utils/Utils.cpp -o /home/william/CPP/Projects/RayTracer2/test/build/Utils.o -I/home/william/CPP/Projects/RayTracer2/ -L/usr/local/lib/ -lcppunit

/home/william/CPP/Projects/RayTracer2/test/build/TestUtils.o: /home/william/CPP/Projects/RayTracer2/test/utils/TestUtils.cpp $(HEADERS)
	g++ -c /home/william/CPP/Projects/RayTracer2/test/utils/TestUtils.cpp -o /home/william/CPP/Projects/RayTracer2/test/build/TestUtils.o -I/home/william/CPP/Projects/RayTracer2/ -L/usr/local/lib/ -lcppunit

/home/william/CPP/Projects/RayTracer2/test/build/Tuple.o : /home/william/CPP/Projects/RayTracer2/src/geometry/Tuple.cpp $(HEADERS)
	g++ -c /home/william/CPP/Projects/RayTracer2/src/geometry/Tuple.cpp -o /home/william/CPP/Projects/RayTracer2/test/build/Tuple.o  -I/home/william/CPP/Projects/RayTracer2/ -L/usr/local/lib/ -lcppunit

/home/william/CPP/Projects/RayTracer2/test/build/TestTuple.o : /home/william/CPP/Projects/RayTracer2/test/geometry/TestTuple.cpp $(HEADERS)
	g++ -c /home/william/CPP/Projects/RayTracer2/test/geometry/TestTuple.cpp -o /home/william/CPP/Projects/RayTracer2/test/build/TestTuple.o  -I/home/william/CPP/Projects/RayTracer2/ -L/usr/local/lib/ -lcppunit

/home/william/CPP/Projects/RayTracer2/test/build/Matrix.o : /home/william/CPP/Projects/RayTracer2/src/geometry/Matrix.cpp $(HEADERS)
	g++ -c /home/william/CPP/Projects/RayTracer2/src/geometry/Matrix.cpp -o /home/william/CPP/Projects/RayTracer2/test/build/Matrix.o  -I/home/william/CPP/Projects/RayTracer2/ -L/usr/local/lib/ -lcppunit

/home/william/CPP/Projects/RayTracer2/test/build/TestMatrix.o : /home/william/CPP/Projects/RayTracer2/test/geometry/TestMatrix.cpp $(HEADERS)
	g++ -c /home/william/CPP/Projects/RayTracer2/test/geometry/TestMatrix.cpp -o /home/william/CPP/Projects/RayTracer2/test/build/TestMatrix.o  -I/home/william/CPP/Projects/RayTracer2/ -L/usr/local/lib/ -lcppunit

/home/william/CPP/Projects/RayTracer2/test/build/Colour.o : /home/william/CPP/Projects/RayTracer2/src/utils/Colour.cpp $(HEADERS)
	g++ -c /home/william/CPP/Projects/RayTracer2/src/utils/Colour.cpp -o /home/william/CPP/Projects/RayTracer2/test/build/Colour.o  -I/home/william/CPP/Projects/RayTracer2/ -L/usr/local/lib/ -lcppunit

/home/william/CPP/Projects/RayTracer2/test/build/TestColour.o : /home/william/CPP/Projects/RayTracer2/test/utils/TestColour.cpp $(HEADERS)
	g++ -c /home/william/CPP/Projects/RayTracer2/test/utils/TestColour.cpp -o /home/william/CPP/Projects/RayTracer2/test/build/TestColour.o  -I/home/william/CPP/Projects/RayTracer2/ -L/usr/local/lib/ -lcppunit

/home/william/CPP/Projects/RayTracer2/test/build/Ray.o : /home/william/CPP/Projects/RayTracer2/src/geometry/Ray.cpp $(HEADERS)
	g++ -c /home/william/CPP/Projects/RayTracer2/src/geometry/Ray.cpp -o /home/william/CPP/Projects/RayTracer2/test/build/Ray.o  -I/home/william/CPP/Projects/RayTracer2/ -L/usr/local/lib/ -lcppunit

/home/william/CPP/Projects/RayTracer2/test/build/TestRay.o : /home/william/CPP/Projects/RayTracer2/test/geometry/TestRay.cpp $(HEADERS)
	g++ -c /home/william/CPP/Projects/RayTracer2/test/geometry/TestRay.cpp -o /home/william/CPP/Projects/RayTracer2/test/build/TestRay.o  -I/home/william/CPP/Projects/RayTracer2/ -L/usr/local/lib/ -lcppunit

/home/william/CPP/Projects/RayTracer2/test/build/Material.o : /home/william/CPP/Projects/RayTracer2/src/scene/world/object/material/Material.cpp $(HEADERS)
	g++ -c /home/william/CPP/Projects/RayTracer2/src/scene/world/object/material/Material.cpp -o /home/william/CPP/Projects/RayTracer2/test/build/Material.o  -I/home/william/CPP/Projects/RayTracer2/ -L/usr/local/lib/ -lcppunit

/home/william/CPP/Projects/RayTracer2/test/build/Shape.o : /home/william/CPP/Projects/RayTracer2/src/scene/world/object/shape/Shape.cpp $(HEADERS)
	g++ -c /home/william/CPP/Projects/RayTracer2/src/scene/world/object/shape/Shape.cpp -o /home/william/CPP/Projects/RayTracer2/test/build/Shape.o  -I/home/william/CPP/Projects/RayTracer2/ -L/usr/local/lib/ -lcppunit

/home/william/CPP/Projects/RayTracer2/test/build/TestMaterial.o : /home/william/CPP/Projects/RayTracer2/test/scene/world/object/material/TestMaterial.cpp $(HEADERS)
	g++ -c /home/william/CPP/Projects/RayTracer2/test/scene/world/object/material/TestMaterial.cpp -o /home/william/CPP/Projects/RayTracer2/test/build/TestMaterial.o  -I/home/william/CPP/Projects/RayTracer2/ -L/usr/local/lib/ -lcppunit
